name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish backend
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: "https://registry.npmjs.org"
      - run: npm install --global yarn
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn bundle
      - run: zip -r bundle.zip bundle
